apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inference-api-key
spec:
  secretStoreRef:
    name: {{ include "openapi-web.fullname" . }}-vault-store
    kind: SecretStore
  target:
    name: inference-api-key
  data:
    - secretKey: NSCALE_INFERENCE_API_KEY
      remoteRef:
        key: {{ .Values.vault.inferenceApiKeyPath }}
        property: api-key
