apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "openapi-web.fullname" . }}-vault-store
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.path }}
      auth:
        appRole:
          path: "approle"
          roleRef:
            key: "id"
            name: {{ .Values.vault.roleName }}
          secretRef:
            key: "secret"
            name: {{ .Values.vault.roleName }}
